<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class AmenitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        // 1. Đảm bảo các Danh mục Tiện ích phong phú & chuẩn mực
        $categories = [
            [
                'code' => 'SPORT_FITNESS',
                'name' => 'Thể Thao & Rèn Luyện Sức Khỏe',
                'icon' => 'activity',
                'desc' => 'Các sân bóng đá, tennis, pickleball, gym, yoga ngoài trời và trong nhà.',
            ],
            [
                'code' => 'COMMUNITY_FACILITIES',
                'name' => 'Tiện Ích Nội Khu Cao Cấp',
                'icon' => 'sparkles',
                'desc' => 'Bể bơi, sảnh đón tiếp sang trọng, đài ngắm cảnh và vườn dạo bộ chân mây.',
            ],
            [
                'code' => 'ENTERTAINMENT_LEISURE',
                'name' => 'Giải Trí & Thư Giãn',
                'icon' => 'gamepad-2',
                'desc' => 'Phòng chiếu phim gia đình, phòng hát karaoke, bida lỗ và khu game VR.',
            ],
            [
                'code' => 'WORK_EDUCATION',
                'name' => 'Làm Việc & Học Tập',
                'icon' => 'book-open',
                'desc' => 'Không gian làm việc chung Coworking Space, thư viện và phòng họp cư dân.',
            ],
            [
                'code' => 'FAMILY_KIDS',
                'name' => 'Gia Đình & Tiệc Ngoài Trời',
                'icon' => 'smile',
                'desc' => 'Vườn nướng BBQ, khu vui chơi trẻ em liên hoàn, bếp nấu tiệc gia đình.',
            ],
            [
                'code' => 'HEALTH_WELLNESS',
                'name' => 'Sức Khỏe & Trị Liệu Spa',
                'icon' => 'heart',
                'desc' => 'Phòng xông hơi đá muối, bồn sục thủy lực Jacuzzi, phòng thiền tĩnh tâm.',
            ],
        ];

        $categoryMap = [];
        foreach ($categories as $cat) {
            $existing = DB::table('amenity_categories')->where('category_code', $cat['code'])->first();
            $catId = $existing ? $existing->id : (string) Str::uuid();

            DB::table('amenity_categories')->updateOrInsert(
                ['category_code' => $cat['code']],
                [
                    'id' => $catId,
                    'category_name' => $cat['name'],
                    'icon_name' => $cat['icon'],
                    'description' => $cat['desc'],
                    'created_at' => $now,
                ]
            );

            $categoryMap[$cat['code']] = $catId;
        }

        // Lấy danh sách tòa nhà có sẵn
        $blockA = DB::table('blocks')->where('block_code', 'BLOCK_A')->value('id');
        $blockB = DB::table('blocks')->where('block_code', 'BLOCK_B')->value('id');
        $blockC = DB::table('blocks')->where('block_code', 'BLOCK_C')->value('id');

        // 2. Danh sách 50 Tiện ích thực tế và đa dạng
        $amenityData = [
            // Thể thao & Rèn luyện (12 tiện ích)
            [
                'code' => 'PICKLEBALL_A1',
                'name' => 'Sân Pickleball Tháp A (Sân 1)',
                'cat' => 'SPORT_FITNESS',
                'block' => $blockA,
                'loc' => 'Tầng thượng Khu thể thao Tháp A',
                'cap' => 4,
                'rate' => 60000,
                'dep' => 100000,
                'adv' => 7,
                'cancel' => 12,
                'approval' => false,
                'active' => true,
                'rules' => 'Mang giày thể thao đế mềm, không mang đồ uống có màu lên mặt sân.',
            ],
            [
                'code' => 'PICKLEBALL_A2',
                'name' => 'Sân Pickleball Tháp A (Sân 2)',
                'cat' => 'SPORT_FITNESS',
                'block' => $blockA,
                'loc' => 'Tầng thượng Khu thể thao Tháp A',
                'cap' => 4,
                'rate' => 60000,
                'dep' => 100000,
                'adv' => 7,
                'cancel' => 12,
                'approval' => false,
                'active' => true,
                'rules' => 'Đặt sân trước ít nhất 2 giờ. Vệ sinh sân sau khi chơi.',
            ],
            [
                'code' => 'BADMINTON_B1',
                'name' => 'Sân Cầu Lông Trong Nhà Số 1',
                'cat' => 'SPORT_FITNESS',
                'block' => $blockB,
                'loc' => 'Nhà đa năng Tầng 2 Tháp B',
                'cap' => 4,
                'rate' => 40000,
                'dep' => 50000,
                'adv' => 7,
                'cancel' => 6,
                'approval' => false,
                'active' => true,
                'rules' => 'Tối đa 4 người/sân, tắt đèn và điều hòa khi hết ca.',
            ],
            [
                'code' => 'BADMINTON_B2',
                'name' => 'Sân Cầu Lông Trong Nhà Số 2',
                'cat' => 'SPORT_FITNESS',
                'block' => $blockB,
                'loc' => 'Nhà đa năng Tầng 2 Tháp B',
                'cap' => 4,
                'rate' => 40000,
                'dep' => 50000,
                'adv' => 7,
                'cancel' => 6,
                'approval' => false,
                'active' => true,
                'rules' => 'Chỉ dành cho cư dân có thẻ hoặc đăng ký qua app.',
            ],
            [
                'code' => 'BASKETBALL_HALF',
                'name' => 'Sân Bóng Rổ Nửa Sân (3x3)',
                'cat' => 'SPORT_FITNESS',
                'block' => null,
                'loc' => 'Công viên trung tâm cạnh Khu C',
                'cap' => 8,
                'rate' => 0,
                'dep' => 0,
                'adv' => 5,
                'cancel' => 4,
                'approval' => false,
                'active' => true,
                'rules' => 'Miễn phí sử dụng cho cư dân. Không bật nhạc lớn sau 22h00.',
            ],
            [
                'code' => 'TABLE_TENNIS_C1',
                'name' => 'Bàn Bóng Bàn Chuyên Nghiệp Số 1',
                'cat' => 'SPORT_FITNESS',
                'block' => $blockC,
                'loc' => 'Phòng thể thao giải trí Tầng 2 Tháp C',
                'cap' => 4,
                'rate' => 0,
                'dep' => 50000,
                'adv' => 3,
                'cancel' => 4,
                'approval' => false,
                'active' => true,
                'rules' => 'Tự bảo quản vợt và bóng. Giữ trật tự chung.',
            ],
            [
                'code' => 'TABLE_TENNIS_C2',
                'name' => 'Bàn Bóng Bàn Chuyên Nghiệp Số 2',
                'cat' => 'SPORT_FITNESS',
                'block' => $blockC,
                'loc' => 'Phòng thể thao giải trí Tầng 2 Tháp C',
                'cap' => 4,
                'rate' => 0,
                'dep' => 50000,
                'adv' => 3,
                'cancel' => 4,
                'approval' => false,
                'active' => true,
                'rules' => 'Sử dụng đúng thời lượng quy định.',
            ],
            [
                'code' => 'YOGA_STUDIO_A',
                'name' => 'Phòng Tập Yoga & Pilates Tháp A',
                'cat' => 'SPORT_FITNESS',
                'block' => $blockA,
                'loc' => 'Tầng 3 Tháp A',
                'cap' => 15,
                'rate' => 80000,
                'dep' => 100000,
                'adv' => 7,
                'cancel' => 12,
                'approval' => false,
                'active' => true,
                'rules' => 'Có sẵn thảm tập và gạch tập. Giữ không gian tĩnh lặng.',
            ],
            [
                'code' => 'YOGA_ZEN_C',
                'name' => 'Phòng Thiền & Yoga Tĩnh Tâm Tháp C',
                'cat' => 'SPORT_FITNESS',
                'block' => $blockC,
                'loc' => 'Tầng 25 Tháp C (Sky Zen Garden)',
                'cap' => 12,
                'rate' => 0,
                'dep' => 0,
                'adv' => 7,
                'cancel' => 8,
                'approval' => false,
                'active' => true,
                'rules' => 'Không mang giày dép vào sàn gỗ, không sử dụng điện thoại phát loa ngoài.',
            ],
            [
                'code' => 'BOXING_ZONE_B',
                'name' => 'Khu Tập Boxing & Thể Lực Đối Kháng',
                'cat' => 'SPORT_FITNESS',
                'block' => $blockB,
                'loc' => 'Tầng hầm B1 Khu thể lực Tháp B',
                'cap' => 6,
                'rate' => 50000,
                'dep' => 50000,
                'adv' => 5,
                'cancel' => 6,
                'approval' => false,
                'active' => true,
                'rules' => 'Đeo găng bảo hộ khi tập luyện, khử khuẩn trang thiết bị sau khi dùng.',
            ],
            [
                'code' => 'MINI_GOLF_ROOF',
                'name' => 'Sân Tập Golf Mini Putting Green',
                'cat' => 'SPORT_FITNESS',
                'block' => $blockA,
                'loc' => 'Rooftop tầng 32 Tháp A',
                'cap' => 4,
                'rate' => 120000,
                'dep' => 200000,
                'adv' => 7,
                'cancel' => 24,
                'approval' => true,
                'active' => true,
                'rules' => 'Không mang gậy sắt đánh mạnh gây hỏng mặt cỏ nhân tạo.',
            ],
            [
                'code' => 'FOOTBALL_FUTSAL',
                'name' => 'Sân Bóng Đá Mini Cỏ Nhân Tạo 5 Người',
                'cat' => 'SPORT_FITNESS',
                'block' => null,
                'loc' => 'Khu thể thao ven hồ công viên ngoài trời',
                'cap' => 12,
                'rate' => 150000,
                'dep' => 200000,
                'adv' => 10,
                'cancel' => 24,
                'approval' => true,
                'active' => true,
                'rules' => 'Sử dụng giày đinh TF, không hút thuốc hoặc mang đồ uống có cồn vào sân.',
            ],

            // Tiện ích Nội khu Cao cấp (8 tiện ích)
            [
                'code' => 'POOL_WARM_FOUR_SEASONS',
                'name' => 'Bể Bơi Bốn Mùa Nước Ấm Trong Nhà',
                'cat' => 'COMMUNITY_FACILITIES',
                'block' => $blockB,
                'loc' => 'Tầng 5 Tháp B',
                'cap' => 35,
                'rate' => 0,
                'dep' => 0,
                'adv' => 7,
                'cancel' => 6,
                'approval' => false,
                'active' => true,
                'rules' => 'Bắt buộc mặc đồ bơi, trẻ em dưới 12 tuổi phải có người lớn đi kèm.',
            ],
            [
                'code' => 'POOL_KIDS_SPLASH',
                'name' => 'Bể Bơi Vầy Trẻ Em & Cầu Trượt Nước',
                'cat' => 'COMMUNITY_FACILITIES',
                'block' => $blockA,
                'loc' => 'Khuôn viên ngoài trời chân Tháp A',
                'cap' => 25,
                'rate' => 0,
                'dep' => 0,
                'adv' => 3,
                'cancel' => 4,
                'approval' => false,
                'active' => true,
                'rules' => 'Mực nước 0.6m, bố mẹ bắt buộc theo sát con trẻ.',
            ],
            [
                'code' => 'SKY_LOUNGE_C',
                'name' => 'Đài Quan Sát & Sky Lounge Tầng 35',
                'cat' => 'COMMUNITY_FACILITIES',
                'block' => $blockC,
                'loc' => 'Tầng 35 Tháp C Sapphire',
                'cap' => 30,
                'rate' => 0,
                'dep' => 0,
                'adv' => 5,
                'cancel' => 6,
                'approval' => false,
                'active' => true,
                'rules' => 'Khu vực ngắm cảnh toàn thành phố. Giữ trật tự và lịch thiệp.',
            ],
            [
                'code' => 'JOGGING_TRACK_SKY',
                'name' => 'Đường Chạy Bộ Trên Không Sky Walk',
                'cat' => 'COMMUNITY_FACILITIES',
                'block' => null,
                'loc' => 'Cầu nối liên tháp Tầng 18 Tháp A - B - C',
                'cap' => 40,
                'rate' => 0,
                'dep' => 0,
                'adv' => 1,
                'cancel' => 1,
                'approval' => false,
                'active' => true,
                'rules' => 'Đi bộ theo đúng làn đường quy định, không đạp xe hoặc trượt ván.',
            ],
            [
                'code' => 'WATER_FOUNTAIN_SQUARE',
                'name' => 'Quảng Trường Nhạc Nước Trung Tâm',
                'cat' => 'COMMUNITY_FACILITIES',
                'block' => null,
                'loc' => 'Quảng trường trung tâm toàn khu đô thị',
                'cap' => 100,
                'rate' => 0,
                'dep' => 0,
                'adv' => 7,
                'cancel' => 12,
                'approval' => true,
                'active' => true,
                'rules' => 'Tổ chức sự kiện cộng đồng cần đăng ký trước với BQL.',
            ],
            [
                'code' => 'TEA_PAVILION_GARDEN',
                'name' => 'Chòi Vọng Cảnh & Thưởng Trà Nhật Bản',
                'cat' => 'COMMUNITY_FACILITIES',
                'block' => $blockB,
                'loc' => 'Vườn Nhật Tầng 4 Tháp B',
                'cap' => 10,
                'rate' => 50000,
                'dep' => 100000,
                'adv' => 7,
                'cancel' => 12,
                'approval' => false,
                'active' => true,
                'rules' => 'Không tổ chức ăn uống đồ nướng dầu mỡ tại khu vực thưởng trà.',
            ],
            [
                'code' => 'COMMUNITY_HALL_A',
                'name' => 'Hội Trường Đa Năng Cư Dân Tháp A',
                'cat' => 'COMMUNITY_FACILITIES',
                'block' => $blockA,
                'loc' => 'Tầng 1 Tháp A',
                'cap' => 80,
                'rate' => 300000,
                'dep' => 1000000,
                'adv' => 14,
                'cancel' => 48,
                'approval' => true,
                'active' => true,
                'rules' => 'Phục vụ họp cư dân, lễ kỷ niệm gia đình. Đặt cọc vệ sinh hoàn lại.',
            ],
            [
                'code' => 'COMMUNITY_HALL_B',
                'name' => 'Hội Trường Sinh Hoạt Cư Dân Tháp B',
                'cat' => 'COMMUNITY_FACILITIES',
                'block' => $blockB,
                'loc' => 'Tầng 1 Tháp B',
                'cap' => 60,
                'rate' => 250000,
                'dep' => 1000000,
                'adv' => 14,
                'cancel' => 48,
                'approval' => true,
                'active' => true,
                'rules' => 'Đảm bảo dọn dẹp sạch sẽ sau khi kết thúc sự kiện.',
            ],

            // Giải trí & Thư giãn (9 tiện ích)
            [
                'code' => 'CINEBOX_VIP_1',
                'name' => 'Rạp Chiếu Phim Gia Đình CineBox 1',
                'cat' => 'ENTERTAINMENT_LEISURE',
                'block' => $blockA,
                'loc' => 'Tầng hầm B1 Tháp A',
                'cap' => 12,
                'rate' => 150000,
                'dep' => 200000,
                'adv' => 7,
                'cancel' => 12,
                'approval' => false,
                'active' => true,
                'rules' => 'Màn hình 150 inch, âm thanh vòm Dolby Atmos. Không mang kẹo cao su.',
            ],
            [
                'code' => 'CINEBOX_VIP_2',
                'name' => 'Rạp Chiếu Phim Gia Đình CineBox 2',
                'cat' => 'ENTERTAINMENT_LEISURE',
                'block' => $blockB,
                'loc' => 'Tầng hầm B1 Tháp B',
                'cap' => 10,
                'rate' => 150000,
                'dep' => 200000,
                'adv' => 7,
                'cancel' => 12,
                'approval' => false,
                'active' => true,
                'rules' => 'Hỗ trợ kết nối Netflix, Apple TV, HDMI cá nhân.',
            ],
            [
                'code' => 'KARAOKE_VIP_A',
                'name' => 'Phòng Hát Karaoke Cách Âm VIP A',
                'cat' => 'ENTERTAINMENT_LEISURE',
                'block' => $blockA,
                'loc' => 'Tầng hầm B1 Tháp A (Khu giải trí)',
                'cap' => 15,
                'rate' => 180000,
                'dep' => 300000,
                'adv' => 7,
                'cancel' => 12,
                'approval' => false,
                'active' => true,
                'rules' => 'Cách âm tiêu chuẩn, không gây ồn ra hành lang. Hoạt động đến 23h00.',
            ],
            [
                'code' => 'KARAOKE_VIP_C',
                'name' => 'Phòng Hát Karaoke Gia Đình VIP C',
                'cat' => 'ENTERTAINMENT_LEISURE',
                'block' => $blockC,
                'loc' => 'Tầng hầm B1 Tháp C',
                'cap' => 12,
                'rate' => 160000,
                'dep' => 300000,
                'adv' => 7,
                'cancel' => 12,
                'approval' => false,
                'active' => true,
                'rules' => 'Dàn âm thanh cao cấp JBL, chọn bài qua màn hình cảm ứng hoặc điện thoại.',
            ],
            [
                'code' => 'BILLIARDS_ROOM_1',
                'name' => 'Bàn Bida Lỗ Aileex Hoàng Gia (Bàn 1)',
                'cat' => 'ENTERTAINMENT_LEISURE',
                'block' => $blockB,
                'loc' => 'CLB Bi-a Tầng 2 Tháp B',
                'cap' => 6,
                'rate' => 50000,
                'dep' => 100000,
                'adv' => 5,
                'cancel' => 6,
                'approval' => false,
                'active' => true,
                'rules' => 'Không đặt đồ uống, tàn thuốc lên nỉ mặt bàn bida.',
            ],
            [
                'code' => 'BILLIARDS_ROOM_2',
                'name' => 'Bàn Bida Lỗ Aileex Hoàng Gia (Bàn 2)',
                'cat' => 'ENTERTAINMENT_LEISURE',
                'block' => $blockB,
                'loc' => 'CLB Bi-a Tầng 2 Tháp B',
                'cap' => 6,
                'rate' => 50000,
                'dep' => 100000,
                'adv' => 5,
                'cancel' => 6,
                'approval' => false,
                'active' => true,
                'rules' => 'Xếp bi lại ngay ngắn sau khi hoàn thành ván đấu.',
            ],
            [
                'code' => 'VR_GAMING_HUB',
                'name' => 'Khu Game Thực Tế Ảo VR & PlayStation 5',
                'cat' => 'ENTERTAINMENT_LEISURE',
                'block' => $blockC,
                'loc' => 'Tầng 3 Tháp C',
                'cap' => 8,
                'rate' => 100000,
                'dep' => 200000,
                'adv' => 5,
                'cancel' => 6,
                'approval' => false,
                'active' => true,
                'rules' => 'Bảo quản cẩn thận kính VR và tay cầm PS5. Đền bù nếu rơi vỡ.',
            ],
            [
                'code' => 'BOARDGAME_CAFE',
                'name' => 'Không Gian Board Game & Cờ Quốc Tế',
                'cat' => 'ENTERTAINMENT_LEISURE',
                'block' => $blockA,
                'loc' => 'Sảnh sinh hoạt Tầng 2 Tháp A',
                'cap' => 16,
                'rate' => 0,
                'dep' => 0,
                'adv' => 3,
                'cancel' => 2,
                'approval' => false,
                'active' => true,
                'rules' => 'Miễn phí hơn 30 bộ cờ vua, cờ tướng, Ma Sói, Catan...',
            ],
            [
                'code' => 'MUSIC_STUDIO',
                'name' => 'Phòng Luyện Nhạc Cụ & Piano Cư Dân',
                'cat' => 'ENTERTAINMENT_LEISURE',
                'block' => $blockB,
                'loc' => 'Tầng 2 Tháp B',
                'cap' => 4,
                'rate' => 80000,
                'dep' => 100000,
                'adv' => 7,
                'cancel' => 12,
                'approval' => false,
                'active' => true,
                'rules' => 'Trang bị đàn Piano cơ Yamaha U3 và trống điện Roland.',
            ],

            // Làm việc & Học tập (6 tiện ích)
            [
                'code' => 'COWORKING_HUB_A',
                'name' => 'Không Gian Làm Việc Coworking Hub A',
                'cat' => 'WORK_EDUCATION',
                'block' => $blockA,
                'loc' => 'Tầng 2 Tháp A',
                'cap' => 25,
                'rate' => 0,
                'dep' => 0,
                'adv' => 3,
                'cancel' => 2,
                'approval' => false,
                'active' => true,
                'rules' => 'Wifi tốc độ cao 500Mbps, ổ cắm điện tại mọi bàn làm việc. Giữ trật tự.',
            ],
            [
                'code' => 'COWORKING_HUB_B',
                'name' => 'Không Gian Làm Việc Sáng Tạo Hub B',
                'cat' => 'WORK_EDUCATION',
                'block' => $blockB,
                'loc' => 'Tầng 2 Tháp B',
                'cap' => 20,
                'rate' => 0,
                'dep' => 0,
                'adv' => 3,
                'cancel' => 2,
                'approval' => false,
                'active' => true,
                'rules' => 'Có máy in, máy scan văn bản tự phục vụ cho cư dân.',
            ],
            [
                'code' => 'MEETING_ROOM_1',
                'name' => 'Phòng Họp Hiện Đại Số 1 (Smart Meeting)',
                'cat' => 'WORK_EDUCATION',
                'block' => $blockA,
                'loc' => 'Tầng 2 Tháp A',
                'cap' => 10,
                'rate' => 100000,
                'dep' => 100000,
                'adv' => 7,
                'cancel' => 12,
                'approval' => false,
                'active' => true,
                'rules' => 'Trang bị màn hình hội nghị trực tuyến 75 inch, camera hội nghị 4K.',
            ],
            [
                'code' => 'MEETING_ROOM_2',
                'name' => 'Phòng Họp Thảo Luận Nhóm Số 2',
                'cat' => 'WORK_EDUCATION',
                'block' => $blockC,
                'loc' => 'Tầng 2 Tháp C',
                'cap' => 8,
                'rate' => 80000,
                'dep' => 100000,
                'adv' => 7,
                'cancel' => 12,
                'approval' => false,
                'active' => true,
                'rules' => 'Bảng từ kính viết bút lông, hệ thống điều hòa riêng biệt.',
            ],
            [
                'code' => 'LIBRARY_RESIDENTS',
                'name' => 'Thư Viện Tri Thức & Không Gian Đọc Sách',
                'cat' => 'WORK_EDUCATION',
                'block' => $blockC,
                'loc' => 'Tầng 1 Tháp C',
                'cap' => 30,
                'rate' => 0,
                'dep' => 0,
                'adv' => 1,
                'cancel' => 1,
                'approval' => false,
                'active' => true,
                'rules' => 'Hơn 2000 đầu sách kinh tế, văn học, kỹ năng sống. Trả sách về đúng kệ.',
            ],
            [
                'code' => 'PODCAST_STUDIO',
                'name' => 'Phòng Thu Âm Podcast & Livestream',
                'cat' => 'WORK_EDUCATION',
                'block' => $blockA,
                'loc' => 'Tầng 2 Tháp A',
                'cap' => 4,
                'rate' => 120000,
                'dep' => 200000,
                'adv' => 7,
                'cancel' => 12,
                'approval' => true,
                'active' => true,
                'rules' => 'Micro thu âm Rode PodMic, đèn livestream studio chuyên nghiệp.',
            ],

            // Gia đình & Tiệc Ngoài Trời (8 tiện ích)
            [
                'code' => 'BBQ_GARDEN_1',
                'name' => 'Vườn Nướng BBQ Ven Hồ Số 1',
                'cat' => 'FAMILY_KIDS',
                'block' => null,
                'loc' => 'Khu dã ngoại công viên bờ hồ',
                'cap' => 15,
                'rate' => 100000,
                'dep' => 300000,
                'adv' => 7,
                'cancel' => 24,
                'approval' => false,
                'active' => true,
                'rules' => 'Có sẵn bếp nướng gas âm bàn, bồn rửa và bàn ghế ăn ngoài trời.',
            ],
            [
                'code' => 'BBQ_GARDEN_2',
                'name' => 'Vườn Nướng BBQ Ven Hồ Số 2',
                'cat' => 'FAMILY_KIDS',
                'block' => null,
                'loc' => 'Khu dã ngoại công viên bờ hồ',
                'cap' => 15,
                'rate' => 100000,
                'dep' => 300000,
                'adv' => 7,
                'cancel' => 24,
                'approval' => false,
                'active' => true,
                'rules' => 'Cư dân tự mang than hoặc dùng bếp nướng điện, dọn rác sau bữa ăn.',
            ],
            [
                'code' => 'BBQ_SKY_B',
                'name' => 'Khu Tiệc Nướng BBQ Trên Mây Tháp B',
                'cat' => 'FAMILY_KIDS',
                'block' => $blockB,
                'loc' => 'Rooftop Tầng 30 Tháp B',
                'cap' => 20,
                'rate' => 150000,
                'dep' => 400000,
                'adv' => 10,
                'cancel' => 24,
                'approval' => true,
                'active' => true,
                'rules' => 'View ngắm pháo hoa và toàn cảnh thành phố, tắt bếp trước 22h30.',
            ],
            [
                'code' => 'COMMUNITY_KITCHEN',
                'name' => 'Bếp Chung Nấu Nướng & Làm Bánh Cư Dân',
                'cat' => 'FAMILY_KIDS',
                'block' => $blockC,
                'loc' => 'Tầng 1 Tháp C',
                'cap' => 10,
                'rate' => 80000,
                'dep' => 200000,
                'adv' => 7,
                'cancel' => 12,
                'approval' => false,
                'active' => true,
                'rules' => 'Trang bị lò nướng bánh Bosch, máy đánh bột, tủ lạnh side-by-side.',
            ],
            [
                'code' => 'KIDZONE_INDOOR',
                'name' => 'Khu Vui Chơi Trẻ Em Liên Hoàn KidZone',
                'cat' => 'FAMILY_KIDS',
                'block' => $blockB,
                'loc' => 'Tầng 1 Tháp B',
                'cap' => 30,
                'rate' => 0,
                'dep' => 0,
                'adv' => 3,
                'cancel' => 2,
                'approval' => false,
                'active' => true,
                'rules' => 'Nhà bóng, cầu trượt xốp an toàn. Bắt buộc đi tất khi vào khu vui chơi.',
            ],
            [
                'code' => 'KIDS_SAND_PARK',
                'name' => 'Công Viên Cát Trắng & Trò Chơi Vận Động',
                'cat' => 'FAMILY_KIDS',
                'block' => null,
                'loc' => 'Sân chơi ngoài trời Tháp C',
                'cap' => 20,
                'rate' => 0,
                'dep' => 0,
                'adv' => 1,
                'cancel' => 1,
                'approval' => false,
                'active' => true,
                'rules' => 'Cát thạch anh tự nhiên đã qua khử trùng, rửa sạch chân tay sau khi chơi.',
            ],
            [
                'code' => 'ART_CRAFT_ROOM',
                'name' => 'Xưởng Sáng Tạo Vẽ Tranh & Gốm Sứ',
                'cat' => 'FAMILY_KIDS',
                'block' => $blockA,
                'loc' => 'Tầng 3 Tháp A',
                'cap' => 12,
                'rate' => 50000,
                'dep' => 50000,
                'adv' => 7,
                'cancel' => 6,
                'approval' => false,
                'active' => true,
                'rules' => 'Có giá vẽ, màu nước và dụng cụ nặn gốm cho các bé và phụ huynh.',
            ],
            [
                'code' => 'OUTDOOR_CAMPING',
                'name' => 'Bãi Cỏ Cắm Trại & Picnic Cuối Tuần',
                'cat' => 'FAMILY_KIDS',
                'block' => null,
                'loc' => 'Đồi cỏ cảnh quan phía Tây',
                'cap' => 25,
                'rate' => 0,
                'dep' => 100000,
                'adv' => 7,
                'cancel' => 12,
                'approval' => false,
                'active' => true,
                'rules' => 'Dựng lều bạt dã ngoại trong ngày, không đốt lửa trại tự phát.',
            ],

            // Sức khỏe & Trị liệu Spa (7 tiện ích)
            [
                'code' => 'SAUNA_SALT_HIMALAYA',
                'name' => 'Phòng Xông Hơi Đá Muối Himalaya Tháp A',
                'cat' => 'HEALTH_WELLNESS',
                'block' => $blockA,
                'loc' => 'Khu Spa Tầng 4 Tháp A',
                'cap' => 8,
                'rate' => 70000,
                'dep' => 100000,
                'adv' => 7,
                'cancel' => 12,
                'approval' => false,
                'active' => true,
                'rules' => 'Xông hơi giải độc cơ thể, nhiệt độ 50-60 độ C. Khuyến cáo tối đa 20 phút/lần.',
            ],
            [
                'code' => 'SAUNA_STEAM_B',
                'name' => 'Phòng Xông Hơi Ướt Thảo Dược Tháp B',
                'cat' => 'HEALTH_WELLNESS',
                'block' => $blockB,
                'loc' => 'Khu Wellness Tầng 5 Tháp B',
                'cap' => 8,
                'rate' => 70000,
                'dep' => 100000,
                'adv' => 7,
                'cancel' => 12,
                'approval' => false,
                'active' => true,
                'rules' => 'Tinh dầu xả chanh tự nhiên, mang theo khăn tắm cá nhân.',
            ],
            [
                'code' => 'JACUZZI_HOT_POOL',
                'name' => 'Bể Sục Thủy Lực Jacuzzi Nước Nóng Tháp A',
                'cat' => 'HEALTH_WELLNESS',
                'block' => $blockA,
                'loc' => 'Cạnh bể bơi Tầng 4 Tháp A',
                'cap' => 10,
                'rate' => 50000,
                'dep' => 50000,
                'adv' => 5,
                'cancel' => 6,
                'approval' => false,
                'active' => true,
                'rules' => 'Hệ thống vòi phun massage lưng và cơ thể, tắm tráng trước khi xuống bể.',
            ],
            [
                'code' => 'JACUZZI_ROOF_C',
                'name' => 'Bể Sục Nước Ấm View Panorama Tháp C',
                'cat' => 'HEALTH_WELLNESS',
                'block' => $blockC,
                'loc' => 'Sky Spa Tầng 30 Tháp C',
                'cap' => 8,
                'rate' => 80000,
                'dep' => 100000,
                'adv' => 7,
                'cancel' => 12,
                'approval' => true,
                'active' => true,
                'rules' => 'Trải nghiệm ngắm hoàng hôn và massage nước ấm thư giãn.',
            ],
            [
                'code' => 'MASSAGE_CHAIR_LOUNGE',
                'name' => 'Phòng Nghỉ Dưỡng & Ghế Massage Cao Cấp',
                'cat' => 'HEALTH_WELLNESS',
                'block' => $blockC,
                'loc' => 'Tầng 2 Tháp C',
                'cap' => 6,
                'rate' => 40000,
                'dep' => 0,
                'adv' => 3,
                'cancel' => 2,
                'approval' => false,
                'active' => true,
                'rules' => '4 ghế massage toàn thân công nghệ không trọng lực tự động.',
            ],
            [
                'code' => 'MEDITATION_GARDEN',
                'name' => 'Vườn Thiền Sỏi Trắng Tĩnh Lặng',
                'cat' => 'HEALTH_WELLNESS',
                'block' => null,
                'loc' => 'Góc tĩnh tâm công viên phía Đông',
                'cap' => 10,
                'rate' => 0,
                'dep' => 0,
                'adv' => 3,
                'cancel' => 1,
                'approval' => false,
                'active' => true,
                'rules' => 'Không gian thiền mở giữa thiên nhiên cây xanh và tiếng suối chảy.',
            ],
            [
                'code' => 'OXYGEN_BAR_LOUNGE',
                'name' => 'Phòng Thư Giãn Oxy Tươi & Trà Thảo Mộc',
                'cat' => 'HEALTH_WELLNESS',
                'block' => $blockB,
                'loc' => 'Tầng 3 Tháp B',
                'cap' => 8,
                'rate' => 60000,
                'dep' => 50000,
                'adv' => 5,
                'cancel' => 6,
                'approval' => false,
                'active' => true,
                'rules' => 'Bổ sung oxy tinh khiết giúp giảm căng thẳng và mệt mỏi sau ngày dài.',
            ],
        ];

        // 3. Tiến hành Insert/Update 50 tiện ích và tạo Khung giờ (Time slots) tự động
        $days = [1, 2, 3, 4, 5, 6, 0]; // Thứ 2 đến Chủ nhật

        $standardSlots = [
            ['start' => '08:00:00', 'end' => '11:30:00', 'label' => 'Khung giờ sáng'],
            ['start' => '14:00:00', 'end' => '17:30:00', 'label' => 'Khung giờ chiều'],
            ['start' => '18:00:00', 'end' => '21:30:00', 'label' => 'Khung giờ tối'],
        ];

        foreach ($amenityData as $item) {
            $catId = $categoryMap[$item['cat']] ?? reset($categoryMap);

            $existing = DB::table('amenities')->where('amenity_code', $item['code'])->first();
            $amId = $existing ? $existing->id : (string) Str::uuid();

            DB::table('amenities')->updateOrInsert(
                ['amenity_code' => $item['code']],
                [
                    'id' => $amId,
                    'category_id' => $catId,
                    'block_id' => $item['block'],
                    'amenity_name' => $item['name'],
                    'location_detail' => $item['loc'],
                    'max_capacity_per_slot' => $item['cap'],
                    'hourly_rate' => $item['rate'],
                    'security_deposit_required' => $item['dep'],
                    'advance_booking_days_limit' => $item['adv'],
                    'min_cancel_hours_before' => $item['cancel'],
                    'requires_admin_approval' => $item['approval'] ? 1 : 0,
                    'rules_and_regulations' => $item['rules'],
                    'cover_image_url' => null,
                    'gallery_images' => json_encode([]),
                    'is_active' => $item['active'] ? 1 : 0,
                    'created_at' => $now->copy()->subDays(rand(1, 90)),
                    'updated_at' => $now,
                    'deleted_at' => null,
                ]
            );

            // Tạo các time slots nếu chưa có
            $slotCount = DB::table('amenity_time_slots')->where('amenity_id', $amId)->count();
            if ($slotCount === 0) {
                foreach ($days as $day) {
                    foreach ($standardSlots as $slot) {
                        DB::table('amenity_time_slots')->insert([
                            'id' => (string) Str::uuid(),
                            'amenity_id' => $amId,
                            'day_of_week' => $day,
                            'slot_start_time' => $slot['start'],
                            'slot_end_time' => $slot['end'],
                            'slot_label' => $slot['label'],
                            'max_bookings' => 1,
                            'is_active' => 1,
                            'created_at' => $now,
                        ]);
                    }
                }
            }
        }

        $totalAmenities = DB::table('amenities')->whereNull('deleted_at')->count();
        $this->command->info("Đã hoàn thành nạp dữ liệu Seeder! Tổng số tiện ích hiện có: {$totalAmenities}");
    }
}
